#!/bin/bash
cp src/example/example.service1.spec.ts src/example/example.service2.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service3.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service4.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service5.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service6.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service7.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service8.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service9.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service10.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service11.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service12.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service13.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service14.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service15.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service16.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service17.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service18.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service19.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service20.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service21.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service22.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service23.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service24.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service25.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service26.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service27.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service28.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service29.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service31.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service32.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service33.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service34.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service35.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service36.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service37.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service38.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service39.spec.ts
cp src/example/example.service1.spec.ts src/example/example.service40.spec.ts
